### ISSUE TITLE
[GITEA IMPORT] getting addres in use errror

### ISSUE THREAD

**Issue by fbrinker** [fbrinker/docker-tileboard#1]
User: JulesBousema
> i ran this command:
> sudo docker run -itd --name=tileboard --restart=always -p 8234:8000 --net=host -v /volume1/docker/tileboard/config.js:/tileboard/config.js fbrinker/tileboard
> 
> this is my log:
> 
> with ServerClass(addr, HandlerClass) as httpd:
> ,  File "/usr/local/lib/python3.9/socketserver.py", line 452, in __init__
> ,    self.server_bind()
> ,  File "/usr/local/lib/python3.9/http/server.py", line 1292, in server_bind
> ,    return super().server_bind()
> ,  File "/usr/local/lib/python3.9/http/server.py", line 138, in server_bind
> ,    socketserver.TCPServer.server_bind(self)
> ,  File "/usr/local/lib/python3.9/socketserver.py", line 466, in server_bind
> ,    self.socket.bind(self.server_address)
> ,OSError: [Errno 98] Address in use
> ,Traceback (most recent call last):
> ,  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
> ,    return _run_code(code, main_globals, None,
> ,  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
> ,    exec(code, run_globals)
> ,  File "/usr/local/lib/python3.9/http/server.py", line 1294, in <module>
> ,    test(
> ,  File "/usr/local/lib/python3.9/http/server.py", line 1249, in test
> ,    with ServerClass(addr, HandlerClass) as httpd:
> ,  File "/usr/local/lib/python3.9/socketserver.py", line 452, in __init__
> ,    self.server_bind()
> ,  File "/usr/local/lib/python3.9/http/server.py", line 1292, in server_bind
> ,    return super().server_bind()
> ,  File "/usr/local/lib/python3.9/http/server.py", line 138, in server_bind
> ,    socketserver.TCPServer.server_bind(self)
> ,  File "/usr/local/lib/python3.9/socketserver.py", line 466, in server_bind
> ,    self.socket.bind(self.server_address)
> ,OSError: [Errno 98] Address in use
> ,Traceback (most recent call last):
> ,  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
> ,    return _run_code(code, main_globals, None,
> ,  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
> ,    exec(code, run_globals)
> ,  File "/usr/local/lib/python3.9/http/server.py", line 1294, in <module>
> ,    test(
> ,  File "/usr/local/lib/python3.9/http/server.py", line 1249, in test
> ,    with ServerClass(addr, HandlerClass) as httpd:
> ,  File "/usr/local/lib/python3.9/socketserver.py", line 452, in __init__
> ,    self.server_bind()
> ,  File "/usr/local/lib/python3.9/http/server.py", line 1292, in server_bind
> ,    return super().server_bind()
> ,  File "/usr/local/lib/python3.9/http/server.py", line 138, in server_bind
> ,    socketserver.TCPServer.server_bind(self)
> ,  File "/usr/local/lib/python3.9/socketserver.py", line 466, in server_bind
> ,    self.socket.bind(self.server_address)
> ,OSError: [Errno 98] Address in use
> ,Traceback (most recent call last):
> ,  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
> ,    return _run_code(code, main_globals, None,
> ,  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
> ,    exec(code, run_globals)
> ,  File "/usr/local/lib/python3.9/http/server.py", line 1294, in <module>
> ,    test(
> ,  File "/usr/local/lib/python3.9/http/server.py", line 1249, in test
> ,    with ServerClass(addr, HandlerClass) as httpd:
> ,  File "/usr/local/lib/python3.9/socketserver.py", line 452, in __init__
> ,    self.server_bind()
> ,  File "/usr/local/lib/python3.9/http/server.py", line 1292, in server_bind
> ,    return super().server_bind()
> ,  File "/usr/local/lib/python3.9/http/server.py", line 138, in server_bind
> ,    socketserver.TCPServer.server_bind(self)
> ,  File "/usr/local/lib/python3.9/socketserver.py", line 466, in server_bind
> ,    self.socket.bind(self.server_address)
> ,OSError: [Errno 98] Address in use
> ,Traceback (most recent call last):
> ,  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
> ,    return _run_code(code, main_globals, None,
> ,  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
> ,    exec(code, run_globals)
> ,  File "/usr/local/lib/python3.9/http/server.py", line 1294, in <module>
> ,    test(
> ,  File "/usr/local/lib/python3.9/http/server.py", line 1249, in test
> ,    with ServerClass(addr, HandlerClass) as httpd:
> ,  File "/usr/local/lib/python3.9/socketserver.py", line 452, in __init__
> ,    self.server_bind()
> ,  File "/usr/local/lib/python3.9/http/server.py", line 1292, in server_bind
> ,    return super().server_bind()
> ,  File "/usr/local/lib/python3.9/http/server.py", line 138, in server_bind
> ,    socketserver.TCPServer.server_bind(self)
> ,  File "/usr/local/lib/python3.9/socketserver.py", line 466, in server_bind
> ,    self.socket.bind(self.server_address)
> ,OSError: [Errno 98] Address in use
> ,Traceback (most recent call last):
> ,  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
> ,    return _run_code(code, main_globals, None,
> ,  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
> ,    exec(code, run_globals)
> ,  File "/usr/local/lib/python3.9/http/server.py", line 1294, in <module>
> ,    test(
> ,  File "/usr/local/lib/python3.9/http/server.py", line 1249, in test
> ,    with ServerClass(addr, HandlerClass) as httpd:
> ,  File "/usr/local/lib/python3.9/socketserver.py", line 452, in __init__
> ,    self.server_bind()
> ,  File "/usr/local/lib/python3.9/http/server.py", line 1292, in server_bind
> ,    return super().server_bind()
> ,  File "/usr/local/lib/python3.9/http/server.py", line 138, in server_bind
> ,    socketserver.TCPServer.server_bind(self)
> ,  File "/usr/local/lib/python3.9/socketserver.py", line 466, in server_bind
> ,    self.socket.bind(self.server_address)
> ,OSError: [Errno 98] Address in use
> ,
> 
> am i doing something wrong?
> 
> 
> EDIT: removed --net=host and changed ports to 8234:8234 and now no more errors.

**Comment by fbrinker** [comment]
Thanks for your update, I'm glad you could solve it. But I'm wondering why 8234:8234 works for you since the port in the container should be 8000 :)
